kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: wp-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: file-sc
spec:
   accessModes:
     - ReadWriteMany
   resources:
     requests:
       storage: 10Gi
